/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thylex.legendarycrafter.frontend.gui;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import org.thylex.legendarycrafter.backend.db.entity.stat.Schematic;
import org.thylex.legendarycrafter.backend.db.entity.stat.SchematicIngredients;
import org.thylex.legendarycrafter.frontend.app.CrafterApp;

/**
 *
 * @author Henrik
 */
public class CalculationFrame extends javax.swing.JFrame {

    private CrafterApp app;
    private Schematic schem;
    private ArrayList<Type0Panel> type0List = new ArrayList<>();
    
    /**
     * Creates new form CalculationGUI
     */
    public CalculationFrame() {
        initComponents();
    }
    
    public CalculationFrame(CrafterApp app, Schematic schematic) {
        initComponents();
        this.app = app;
        this.schem = schematic;
        
        prepareLayout();
        
    }
    
    private void prepareLayout() {
        this.setTitle(schem.getSchematicName());
        for (SchematicIngredients si : schem.getIngredients()) {
            System.out.println("Adding: " + si.getIngredientName());
            int nrIngreds = schem.getIngredients().size();
            this.getContentPane().setLayout(new GridLayout(nrIngreds, 1));
            if (si.getIngredientType() == 0) {
                Type0Panel panel = new Type0Panel();
                panel.setBorder(new TitledBorder(si.getIngredientName().replace("_", " ")));
                // TODO: expand this using resourceGroup
                panel.setRequiredText(si.getIngredientObject());
                panel.setAmountLabel(si.getIngredientQuantity().toString() + " x");
                // TODO: Set combobocmodel of materials
                this.getContentPane().add(panel, BorderLayout.CENTER);
                type0List.add(panel);
            }
            if (si.getIngredientType() == 3) {
                Type3Panel panel = new Type3Panel();
                panel.setBorder(new TitledBorder("Sub component"));
                panel.setRequiredText(si.getIngredientName().replace("_", " "));
                this.getContentPane().add(panel, BorderLayout.CENTER);
            }
            //this.getContentPane().add(addIngredient(new JPanel(), si), BorderLayout.CENTER);
        }
        this.validate();
        this.setVisible(true);
    }
    
    private JPanel addIngredient(JPanel panel, SchematicIngredients si) {
        panel.setBorder(new TitledBorder(si.getIngredientName().replace("_", " ")));
        
        JLabel contrLabel = new JLabel("Contribution");
        JTextField contrText = new JTextField(si.getIngredientContribution().toString());
        contrLabel.setLabelFor(contrText);
        panel.add(contrLabel);
        panel.add(contrText);
        
        JLabel typeLabel = new JLabel("Type");
        JTextField typeText = new JTextField(si.getIngredientType().toString());
        typeLabel.setLabelFor(typeText);
        panel.add(typeLabel);
        panel.add(typeText);
        
        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
