/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thylex.legendarycrafter.frontend.gui;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumnModel;
import org.thylex.legendarycrafter.backend.db.entity.inv.Resource;
import org.thylex.legendarycrafter.frontend.app.CrafterApp;

/**
 *
 * @author Henrik
 */
public class CrafterGUI extends javax.swing.JFrame implements TableModelListener {

    private CrafterApp app = null;
    private JTabbedPane tabPane = null;
    private JPanel invPanel = null;
    private JTable invTable = null;
    private JPanel schPanel = null;

    /**
     * Creates new form CrafterGUI
     */
    public CrafterGUI(CrafterApp app) {
        this.app = app;
        initComponents();
        setTitle("Legendary Crafter");

        // Create base Tabbed Pane
        tabPane = new JTabbedPane(JTabbedPane.TOP);

        // Create base Panel for Inventory display
        invPanel = new JPanel();
        invPanel.setLayout(new BorderLayout());

        // Top controls for inventory tab
        invPanel.add(new JLabel("Inventory tab"), BorderLayout.PAGE_START);

        // Inventory Table display
        invTable = new JTable(new InventoryTableModel(app.getAllInv()));
//        invTable.addFocusListener(new FocusAdapter() {
//            @Override
//            public void focusLost(FocusEvent e) {
//                TableCellEditor tce = invTable.getCellEditor();
//                if (tce != null) {
//                    tce.stopCellEditing();
//                }
//            }
//        });
        invTable.setFillsViewportHeight(false);
        invTable.getModel().addTableModelListener(this);
        setInvColumnWidth();
        invPanel.add(new JScrollPane(invTable), BorderLayout.CENTER);

        // Add inventory to Tabbed view
        tabPane.addTab("Inventory", invPanel);

        // Create base Panel for Schematics view
        schPanel = new JPanel();
        schPanel.setLayout(new BorderLayout());

        // Add controls for schematics work
        schPanel.add(new JLabel("Schematics tab"), BorderLayout.PAGE_START);

        // Add schematics Panel to Tabbed vie
        tabPane.addTab("Schematics", schPanel);

        // Add Tabbed Pane to base Frame
        this.getContentPane().setLayout(new GridLayout(1, 1));
        this.getContentPane().add(tabPane);

        validate();
        this.setVisible(true);
    }

    @Override

    public void tableChanged(TableModelEvent e) {
        int col = e.getColumn();
        int row = e.getFirstRow();
        InventoryTableModel model = (InventoryTableModel) e.getSource();
        String name = (String) model.getValueAt(row, 0);
        Integer newAmount = (Integer) invTable.getValueAt(row, col);

        Resource res = app.getInvByName(name);
        if (res != null) {
            res.setAmount(newAmount);
            app.updateInv(res);
            System.out.println("Amount of " + name + " changed to " + newAmount.toString());
        } else {
            System.out.println("ERROR: Unable to find resource by name: " + name);
        }

    }

    private void setInvColumnWidth() {
        TableColumnModel cModel = invTable.getColumnModel();
        for (int i = 0; i < cModel.getColumnCount(); i++) {
            switch (i) {
                case 0:
                    cModel.getColumn(i).setPreferredWidth(100);
                    break;
                case 1:
                    cModel.getColumn(i).setPreferredWidth(200);
                    break;
                case 13:
                    cModel.getColumn(i).setPreferredWidth(100);
                    break;
                default:
                    cModel.getColumn(i).setPreferredWidth(50);
                    break;
            }
        }
    }

    public void refresh() {
        invTable.setModel(new InventoryTableModel(app.getAllInv()));
        invTable.getModel().addTableModelListener(this);
        setInvColumnWidth();
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItem1.setText("Import");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        app.importFromGH();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        app.close();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrafterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrafterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrafterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrafterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new CrafterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

}
